plugins {
    id 'com.android.application'
}

def releaseKeystorePath = System.getenv('ANDROID_KEYSTORE_PATH')

android {
    namespace 'com.aulauas.hangar'
    compileSdk 35

    defaultConfig {
        applicationId 'com.aulauas.hangar'
        minSdk 29
        targetSdk 35
        versionCode 8
        versionName '8.0'
    }

    signingConfigs {
        if (releaseKeystorePath) {
            release {
                storeFile file(releaseKeystorePath)
                storePassword System.getenv('ANDROID_KEYSTORE_PASSWORD')
                keyAlias System.getenv('ANDROID_KEY_ALIAS')
                keyPassword System.getenv('ANDROID_KEY_PASSWORD')
            }
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            if (releaseKeystorePath) signingConfig signingConfigs.release
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}
